### ISSUE TITLE
Appveyor fails because of weeder

### ISSUE THREAD

**Issue by hanjoosten** [ndmitchell/weeder#36]
Since two days, all buids of the Ampersand project at Appveyor fail ([see this log](https://ci.appveyor.com/project/hanjoosten/ampersand/build/build.1337-development)) because of the use of weeder. On Travis however, where I do not use weeder, the project builds fine. 

There is something wrong after building yaml-0.8.28. It fails with the message `Command exited with code 1`. On my local windows machine, I cannot reproduce this. This issue breaks our automatic release job.

**Comment by ndmitchell** [comment]
So it seems to be compiling `yaml` using `stack`  with GHC 8.4.1 is the real issue - the fact Weeder causes that to happen is just the thing triggering it - not the underlying cause. About 2 days ago Stack nightly switched to GHC 8.4.1, so that will be what is triggering the issue. It's a problem, and one that might be worth reporting to @snoyberg in his capacity as `yaml` maintainer.

One way to sidestep the issue is just use the Weeder binary as recommended in the user manual. I see you have that code, but it's commented out - any reason why?

**Comment by ndmitchell** [comment]
I raised the general problem of Windows nightly failures at https://github.com/fpco/stackage/issues/3385 - since I just got one with an unrelated project.

**Comment by hanjoosten** [comment]
Thanks for looking into this issue. And also thanks for reminding me of the sidestep. I didn't get the sidestep to work initially, because back then I didn't understand how to do it and it [gave an error](https://ci.appveyor.com/project/hanjoosten/ampersand/build/build.1344-buildProblem). I figured out that I could make `stack` do the job.
The issue with the windows failures with nightly is a separate issue, so this issue can be closed.
